
[config]
version_check = false

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "random"]
set = true

[templates.hyprland]
input_path = 'templates/colors-hyprland'
output_path = "~/.cache/colors/hyprland/colors.conf"

[templates.shell]
input_path = 'templates/colors-shell'
output_path = '~/.cache/colors/shell/colors'

[templates.foot]
input_path = 'templates/foot'
output_path = '~/.cache/colors/foot/colors.ini'

[templates.helix]
input_path = 'templates/helix'
output_path = '~/.config/helix/themes/matugen.toml'

[templates.gtk]
input_path = 'templates/gtk'
output_path = '~/.cache/colors/gtk/colors.css'

[templates.colors]
input_path = 'templates/colors'
output_path = '~/.cache/colors/colors.css'

[templates.greetd]
input_path = 'templates/colors'
output_path = '/etc/greetd/colors.css'
