[[language]]
name = "toml"
roots = ["."]


[[language]]
name = "rust"
[language-server.rust-analyzer]
config = { procMacro = { ignored = { leptos_macro = [
    # Optional:
    # "component",
    # "server"
] } } }

[[language]]
name = "slint"
file-types = ["slint"]
language-servers =  [ "slint-lsp" ]
