[background]
path = "/usr/share/wallpapers/a_waterfall_over_rocks.jpg"
fit = "Fill"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Bibata-Modern-Ice"
font_name = "Readex Pro"
icon_theme_name = "Papirus"
theme_name = "Adwaita"

[commands]
reboot = [
    "systemctl",
    "reboot",
]
poweroff = [
    "systemctl",
    "poweroff",
]

[appearance]
greeting_msg = "Welcome back!"

[widget.clock]
format = "%a %H:%M"
resolution = "500ms"
label_width = 150
