#  ┏┓┳┳┏┳┓┏┓┏┓┏┳┓┏┓┳┓┏┳┓
#  ┣┫┃┃ ┃ ┃┃┗┓ ┃ ┣┫┣┫ ┃ 
#  ┛┗┗┛ ┻ ┗┛┗┛ ┻ ┛┗┛┗ ┻ 
#                       

#-----------------XDPH-----------------#
#--------------------------------------#
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # for XDPH
exec-once = dbus-update-activation-environment --systemd --all # for XDPH
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # for XDPH

#-----------clipboard manager------------#
#----------------------------------------#

exec-once = uwsm app -t service -s b -- clipse -listen

#-------------bar, wallpaper & notification daemon--------------#
#---------------------------------------------------------------#
# 
exec-once = uwsm app  -- qs -c bareeq

#-----------authentication agent------------#
#-------------------------------------------#
# systemctl --user enable --now hyprpolkitagent.service


