#  ┓ ┏┳┳┓┳┓┏┓┓ ┏  ┳┓┳┳┓ ┏┓┏┓
#  ┃┃┃┃┃┃┃┃┃┃┃┃┃  ┣┫┃┃┃ ┣ ┗┓
#  ┗┻┛┻┛┗┻┛┗┛┗┻┛  ┛┗┗┛┗┛┗┛┗┛
#                           
#--------------states of specific applications-------------------#
#----------------------------------------------------------------#
windowrule {
  name = windowrule-1
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

windowrule {
  name = windowrule-2
  opacity = 0.84 override 0.84 override
  match:title = (.*)
}

windowrule {
  name = windowrule-3
  float = on
  size = 689 400
  match:class = ^(com.saivert.pwvucontrol)$
}

windowrule {
  name = windowrule-4
  float = on
  opacity = 0.9 0.7
  size = 826 800
  match:class = ^(io.github.kaii_lb.Overskride)$
}

windowrule {
  name = windowrule-5
  float = on
  match:class = ^(nm-connection-editor)$
}

windowrule {
  name = windowrule-6
  float = on
  match:class = ^(clipse)$ # ensure you have a floating window class set if you want this behavior
}

windowrule {
  name = windowrule-7
  float = on
  match:class = ^(nmtui)$
}

windowrule {
  name = windowrule-8
  float = on
  match:title = ^(Choose a Wallpaper)$
}

windowrule {
  name = windowrule-9
  float = on
  match:title = ^((.* Properties))$
}

windowrule {
  name = windowrule-10
  float = on
  match:title = ^(Library)$
}


#--------------opacity of specific applications------------------#
#----------------------------------------------------------------#
windowrule {
  name = windowrule-11
  opacity = 1 0.8
  match:class = ^(libreoffice-(.*))$
}

windowrule {
  name = windowrule-12
  opacity = 0.9 0.7
  match:class = ^(nemo)$
}

windowrule {
  name = windowrule-13
  opacity = 0.9 0.7
  match:class = ^(foot)$
}


#---------------sizes of specific applications in floating mode-------------------#
#---------------------------------------------------------------------------------#
windowrule {
  name = windowrule-14
  size = 752 852
  match:class = (clipse) # set the size of the window as necessary
}

windowrule {
  name = windowrule-15
  size = 622 652
  match:class = (nmtui) # set the size of the window as necessary
}

windowrule {
  name = windowrule-16
  size = 1200 800
  match:title = (Choose a Wallpaper) # set the size of the window as necessary
}


#---------------browser picture in picture----------------------------------------#
#---------------------------------------------------------------------------------#
windowrule {
  name = windowrule-17
  float = on
  pin = on
  move = ((monitor_w*0.725)) ((monitor_h*0.7))
  size = 520 320
  match:title = ^(Picture-in-Picture)$
}



#-----------------XWayland Specific-----------------------------------------------#
#---------------------------------------------------------------------------------#
windowrule {
  name = windowrule-18
  # no_blur = on
  border_size = 0
  no_shadow = on
  rounding = 0
  # opacity = 0.98 override 0.98 override
  match:xwayland = 1
}




#  ┓ ┏┓┓┏┏┓┳┓  ┳┓┳┳┓ ┏┓┏┓
#  ┃ ┣┫┗┫┣ ┣┫  ┣┫┃┃┃ ┣ ┗┓
#  ┗┛┛┗┗┛┗┛┛┗  ┛┗┗┛┗┛┗┛┗┛
#                        

#-----------Noctalia-------------#
#------------------------------#
# layerrule {
#   name = layerrule-1
#   blur = on
#   ignore_alpha = 0.5
#   match:namespace = noctalia-bar-content-eDP-1
# }

# layerrule {
#   name = layerrule-2
#   blur = on
#   ignore_alpha = 0.5
#   match:namespace = noctalia-background-eDP-1
# }

