#!/usr/bin/env bash

declare IMAGE=$(swww query | head -1 | awk -F 'image: ' '{print $2}')
declare COLOR_SCHEME=$(gsettings get org.gnome.desktop.interface color-scheme | rg -o dark)

switch_scheme() {
  if [[ -n "$COLOR_SCHEME"  ]]; then
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'
    gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Light' 
    gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
    hyprctl setcursor Bibata-Modern-Classic 24 > /dev/null 
    echo "exec-once=hyprctl setcursor Bibata-Modern-Classic 24" >> $XDG_CONFIG_HOME/colors/hyprland/colors.conf &
  else
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
    gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
    gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
    hyprctl setcursor Bibata-Modern-Ice 24 > /dev/null 
    echo "exec-once=hyprctl setcursor Bibata-Modern-Ice 24" >> $XDG_CONFIG_HOME/colors/hyprland/colors.conf &
  fi
}
switch_scheme && exit 0
