#!/usr/bin/env bash
apply_term() {

  for file in /dev/pts/*; do
    if [[ $file =~ ^/dev/pts/[0-9]+$ ]]; then
      cat $XDG_CONFIG_HOME/colors/shell/colors >"$file"
    fi
  done
}

apply_term && exec "$SHELL"
