#!/usr/bin/bash

declare IMAGE=$(swww query | head -1 | awk -F 'image: ' '{print $2}')
declare COLOR_SCHEME=$(gsettings get org.gnome.desktop.interface color-scheme | rg -o dark)

switch_scheme() {
  if [[ -n "$COLOR_SCHEME"  ]]; then
    matugen image "$IMAGE" --mode 'light'
  else
    matugen image "$IMAGE" --mode 'dark'
  fi
}

switch_scheme && exit 0
