#!/usr/bin/env bash

declare WALLPAPER_FOLDER="/usr/share/wallpapers/" #choose wallpaper folder; and don't remove the trailing slash
declare IMAGE=$(zenity --width 1200 --height 800 --file-selection --title="Choose a Wallpaper" --filename "$WALLPAPER_FOLDER")
declare COLOR_SCHEME=$(gsettings get org.gnome.desktop.interface color-scheme | rg -o "(dark|light)")
declare CURSOR_THEME=$(gsettings get org.gnome.desktop.interface cursor-theme)
declare THEME=$(gsettings get org.gnome.desktop.interface gtk-theme)


switch_matugen() {
  matugen image $IMAGE --mode $COLOR_SCHEME
  # gsettings set org.gnome.desktop.interface gtk-theme ''
  # gsettings set org.gnome.desktop.interface gtk-theme $THEME
  # echo "exec-once=hyprctl setcursor $CURSOR_THEME 24" | tee -a $XDG_CONFIG_HOME/colors/hyprland/colors.conf
}

if [[ -z $IMAGE ]]; then
  exit 1
else
  switch_matugen && exit 0
fi
