[symlinks]
"dunst/dunstrc" = "/home/akram/.config/dunst/dunstrc"
"fish/config.fish" = "/home/akram/.config/fish/config.fish"
"fish/fish_variables" = "/home/akram/.config/fish/fish_variables"
"fish/functions/fish_prompt.fish" = "/home/akram/.config/fish/functions/fish_prompt.fish"
"fontconfig/fonts.conf" = "/home/akram/.config/fontconfig/fonts.conf"
"foot/foot.ini" = "/home/akram/.config/foot/foot.ini"
"foot/wrapper" = "/home/akram/.config/foot/wrapper"
"helix/config.toml" = "/home/akram/.config/helix/config.toml"
"helix/languages.toml" = "/home/akram/.config/helix/languages.toml"
"hypr/hypridle.conf" = "/home/akram/.config/hypr/hypridle.conf"
"hypr/hyprland.conf" = "/home/akram/.config/hypr/hyprland.conf"
"hypr/hyprlock/battery.sh" = "/home/akram/.config/hypr/hyprlock/battery.sh"
"hypr/hyprlock.conf" = "/home/akram/.config/hypr/hyprlock.conf"
"hypr/local/local.conf" = "/home/akram/.config/hypr/local/local.conf"
"hypr/modules/animations/END-4.conf" = "/home/akram/.config/hypr/modules/animations/END-4.conf"
"hypr/modules/animations/HYDE - Vertical.conf" = "/home/akram/.config/hypr/modules/animations/HYDE - Vertical.conf"
"hypr/modules/animations/HYDE - default.conf" = "/home/akram/.config/hypr/modules/animations/HYDE - default.conf"
"hypr/modules/animations/HYDE - minimal-1.conf" = "/home/akram/.config/hypr/modules/animations/HYDE - minimal-1.conf"
"hypr/modules/animations/HYDE - minimal-2.conf" = "/home/akram/.config/hypr/modules/animations/HYDE - minimal-2.conf"
"hypr/modules/animations/HYDE - optimized.conf" = "/home/akram/.config/hypr/modules/animations/HYDE - optimized.conf"
"hypr/modules/animations/ML4W - classic.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - classic.conf"
"hypr/modules/animations/ML4W - dynamic.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - dynamic.conf"
"hypr/modules/animations/ML4W - fast.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - fast.conf"
"hypr/modules/animations/ML4W - high.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - high.conf"
"hypr/modules/animations/ML4W - moving.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - moving.conf"
"hypr/modules/animations/ML4W - standard.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - standard.conf"
"hypr/modules/animations/Mahaveer - me-1.conf" = "/home/akram/.config/hypr/modules/animations/Mahaveer - me-1.conf"
"hypr/modules/animations/Mahaveer - me-2.conf" = "/home/akram/.config/hypr/modules/animations/Mahaveer - me-2.conf"
"hypr/modules/animations/Matuprland optimized.conf" = "/home/akram/.config/hypr/modules/animations/Matuprland optimized.conf"
"hypr/modules/animations/default - v2.conf" = "/home/akram/.config/hypr/modules/animations/default - v2.conf"
"hypr/modules/animations/default.conf" = "/home/akram/.config/hypr/modules/animations/default.conf"
"hypr/modules/animations/disabled.conf" = "/home/akram/.config/hypr/modules/animations/disabled.conf"
"hypr/modules/animations.conf" = "/home/akram/.config/hypr/modules/animations.conf"
"hypr/modules/autostart.conf" = "/home/akram/.config/hypr/modules/autostart.conf"
"hypr/modules/decorations.conf" = "/home/akram/.config/hypr/modules/decorations.conf"
"hypr/modules/inputs.conf" = "/home/akram/.config/hypr/modules/inputs.conf"
"hypr/modules/keybinds.conf" = "/home/akram/.config/hypr/modules/keybinds.conf"
"hypr/modules/monitors.conf" = "/home/akram/.config/hypr/modules/monitors.conf"
"hypr/modules/programs.conf" = "/home/akram/.config/hypr/modules/programs.conf"
"hypr/modules/settings.conf" = "/home/akram/.config/hypr/modules/settings.conf"
"hypr/modules/variables.conf" = "/home/akram/.config/hypr/modules/variables.conf"
"hypr/modules/windowrules.conf" = "/home/akram/.config/hypr/modules/windowrules.conf"
"hypr/modules/workspacerules.conf" = "/home/akram/.config/hypr/modules/workspacerules.conf"
"hypr/scripts/Discord/dark.sh" = "/home/akram/.config/hypr/scripts/Discord/dark.sh"
"hypr/scripts/Rofi-launcher.sh" = "/home/akram/.config/hypr/scripts/Rofi-launcher.sh"
"hypr/scripts/Weather.py" = "/home/akram/.config/hypr/scripts/Weather.py"
"hypr/scripts/Weather.sh" = "/home/akram/.config/hypr/scripts/Weather.sh"
"hypr/scripts/airplaneMode.sh" = "/home/akram/.config/hypr/scripts/airplaneMode.sh"
"hypr/scripts/backlight.sh" = "/home/akram/.config/hypr/scripts/backlight.sh"
"hypr/scripts/batterynotify.sh" = "/home/akram/.config/hypr/scripts/batterynotify.sh"
"hypr/scripts/brightnesscontrol.sh" = "/home/akram/.config/hypr/scripts/brightnesscontrol.sh"
"hypr/scripts/convert_css.py" = "/home/akram/.config/hypr/scripts/convert_css.py"
"hypr/scripts/dark_light" = "/home/akram/.config/hypr/scripts/dark_light"
"hypr/scripts/dontkillsteam.sh" = "/home/akram/.config/hypr/scripts/dontkillsteam.sh"
"hypr/scripts/expand_toolbar" = "/home/akram/.config/hypr/scripts/expand_toolbar"
"hypr/scripts/killActiveProcess.sh" = "/home/akram/.config/hypr/scripts/killActiveProcess.sh"
"hypr/scripts/kitty-colors/kitty-dark.py" = "/home/akram/.config/hypr/scripts/kitty-colors/kitty-dark.py"
"hypr/scripts/kitty-colors/kitty-light.py" = "/home/akram/.config/hypr/scripts/kitty-colors/kitty-light.py"
"hypr/scripts/kitty-colors/kitty-light.py.save" = "/home/akram/.config/hypr/scripts/kitty-colors/kitty-light.py.save"
"hypr/scripts/kitty-colors/selector.py" = "/home/akram/.config/hypr/scripts/kitty-colors/selector.py"
"hypr/scripts/main-wall-scirpt/waypaper" = "/home/akram/.config/hypr/scripts/main-wall-scirpt/waypaper"
"hypr/scripts/matugenMagick.sh" = "/home/akram/.config/hypr/scripts/matugenMagick.sh"
"hypr/scripts/mute.sh" = "/home/akram/.config/hypr/scripts/mute.sh"
"hypr/scripts/parse_css_to_hyprland.py" = "/home/akram/.config/hypr/scripts/parse_css_to_hyprland.py"
"hypr/scripts/refresh.sh" = "/home/akram/.config/hypr/scripts/refresh.sh"
"hypr/scripts/resetxdgportal.sh" = "/home/akram/.config/hypr/scripts/resetxdgportal.sh"
"hypr/scripts/rofi_light_dark/darkcolors.sh" = "/home/akram/.config/hypr/scripts/rofi_light_dark/darkcolors.sh"
"hypr/scripts/rofi_light_dark/lightcolors.sh" = "/home/akram/.config/hypr/scripts/rofi_light_dark/lightcolors.sh"
"hypr/scripts/rofi_light_dark/rofi_dark.sh" = "/home/akram/.config/hypr/scripts/rofi_light_dark/rofi_dark.sh"
"hypr/scripts/rofi_light_dark/rofi_dark2.sh" = "/home/akram/.config/hypr/scripts/rofi_light_dark/rofi_dark2.sh"
"hypr/scripts/rofi_light_dark/rofi_light.sh" = "/home/akram/.config/hypr/scripts/rofi_light_dark/rofi_light.sh"
"hypr/scripts/rofi_light_dark/rofi_light2.sh" = "/home/akram/.config/hypr/scripts/rofi_light_dark/rofi_light2.sh"
"hypr/scripts/rofi_style1.sh" = "/home/akram/.config/hypr/scripts/rofi_style1.sh"
"hypr/scripts/rofi_style2.sh" = "/home/akram/.config/hypr/scripts/rofi_style2.sh"
"hypr/scripts/rofi_style3.sh" = "/home/akram/.config/hypr/scripts/rofi_style3.sh"
"hypr/scripts/rofi_style5.sh" = "/home/akram/.config/hypr/scripts/rofi_style5.sh"
"hypr/scripts/rofi_style6.sh" = "/home/akram/.config/hypr/scripts/rofi_style6.sh"
"hypr/scripts/screenshot.sh" = "/home/akram/.config/hypr/scripts/screenshot.sh"
"hypr/scripts/songdetail.sh" = "/home/akram/.config/hypr/scripts/songdetail.sh"
"hypr/scripts/sounds.sh" = "/home/akram/.config/hypr/scripts/sounds.sh"
"hypr/scripts/tools/expand" = "/home/akram/.config/hypr/scripts/tools/expand"
"hypr/scripts/tools/expand2" = "/home/akram/.config/hypr/scripts/tools/expand2"
"hypr/scripts/tools/start_dyn" = "/home/akram/.config/hypr/scripts/tools/start_dyn"
"hypr/scripts/tools/test.log" = "/home/akram/.config/hypr/scripts/tools/test.log"
"hypr/scripts/touchpad_toggle.sh" = "/home/akram/.config/hypr/scripts/touchpad_toggle.sh"
"hypr/scripts/volume.sh" = "/home/akram/.config/hypr/scripts/volume.sh"
"hypr/scripts/volumecontrol.sh" = "/home/akram/.config/hypr/scripts/volumecontrol.sh"
"hypr/scripts/wal_spotify/wal_spicetify_dark" = "/home/akram/.config/hypr/scripts/wal_spotify/wal_spicetify_dark"
"hypr/scripts/wal_spotify/wal_spicetify_dark.py" = "/home/akram/.config/hypr/scripts/wal_spotify/wal_spicetify_dark.py"
"hypr/scripts/wal_spotify/wal_spicetify_light" = "/home/akram/.config/hypr/scripts/wal_spotify/wal_spicetify_light"
"hypr/scripts/wal_spotify/wal_spicetify_light.py" = "/home/akram/.config/hypr/scripts/wal_spotify/wal_spicetify_light.py"
"hypr/scripts/wall" = "/home/akram/.config/hypr/scripts/wall"
"hypr/scripts/wallSelect.sh" = "/home/akram/.config/hypr/scripts/wallSelect.sh"
"hypr/scripts/wallpaperSelect.sh" = "/home/akram/.config/hypr/scripts/wallpaperSelect.sh"
"hypr/scripts/waybar script/DEFAULT" = "/home/akram/.config/hypr/scripts/waybar script/DEFAULT"
"hypr/scripts/waybar script/SIDE BAR" = "/home/akram/.config/hypr/scripts/waybar script/SIDE BAR"
"hypr/scripts/waybar script/WINCLOUD" = "/home/akram/.config/hypr/scripts/waybar script/WINCLOUD"
"hypr/scripts/waybar script/pixelcloud" = "/home/akram/.config/hypr/scripts/waybar script/pixelcloud"
"hypr/scripts/waybarSelect.sh" = "/home/akram/.config/hypr/scripts/waybarSelect.sh"
"hypr/scripts/weather.py" = "/home/akram/.config/hypr/scripts/weather.py"
"hypr/scripts/wlogout.sh" = "/home/akram/.config/hypr/scripts/wlogout.sh"
"matugen/config.toml" = "/home/akram/.config/matugen/config.toml"
"matugen/templates/colors" = "/home/akram/.config/matugen/templates/colors"
"matugen/templates/colors-hyprland" = "/home/akram/.config/matugen/templates/colors-hyprland"
"matugen/templates/dunst/dunst_dark" = "/home/akram/.config/matugen/templates/dunst/dunst_dark"
"matugen/templates/dunst/dunst_light" = "/home/akram/.config/matugen/templates/dunst/dunst_light"
"matugen/templates/gtk" = "/home/akram/.config/matugen/templates/gtk"
"matugen/templates/qtct-theme.conf" = "/home/akram/.config/matugen/templates/qtct-theme.conf"
"matugen/templates/shell/applycol.sh" = "/home/akram/.config/matugen/templates/shell/applycol.sh"
"matugen/templates/shell/dark" = "/home/akram/.config/matugen/templates/shell/dark"
"matugen/templates/shell/light" = "/home/akram/.config/matugen/templates/shell/light"
"matugen/templates/shell/shell-dark" = "/home/akram/.config/matugen/templates/shell/shell-dark"
"matugen/templates/shell/shell-light" = "/home/akram/.config/matugen/templates/shell/shell-light"
"nushell/config.nu" = "/home/akram/.config/nushell/config.nu"
"nushell/env.nu" = "/home/akram/.config/nushell/env.nu"
"nushell/history.txt" = "/home/akram/.config/nushell/history.txt"
"qt6ct/colors/matugen.conf" = "/home/akram/.config/qt6ct/colors/matugen.conf"
"qt6ct/qt6ct.conf" = "/home/akram/.config/qt6ct/qt6ct.conf"
"qt6ct/style-colors.conf" = "/home/akram/.config/qt6ct/style-colors.conf"
"sherlock/config.toml" = "/home/akram/.config/sherlock/config.toml"
"sherlock/fallback.json" = "/home/akram/.config/sherlock/fallback.json"
"sherlock/main.css" = "/home/akram/.config/sherlock/main.css"
"sherlock/sherlock_alias.json" = "/home/akram/.config/sherlock/sherlock_alias.json"
"sherlock/sherlockignore" = "/home/akram/.config/sherlock/sherlockignore"
"starship/starship.toml" = "/home/akram/.config/starship/starship.toml"
"waybar/config.jsonc" = "/home/akram/.config/waybar/config.jsonc"
"waybar/scripts/Colorpicker.sh" = "/home/akram/.config/waybar/scripts/Colorpicker.sh"
"waybar/scripts/Weather.sh" = "/home/akram/.config/waybar/scripts/Weather.sh"
"waybar/style.css" = "/home/akram/.config/waybar/style.css"
"wezterm.lua" = "/home/akram/.wezterm.lua"
"xdg-terminals.list" = "/home/akram/.config/xdg-terminals.list"
"zed/keymap.json" = "/home/akram/.config/zed/keymap.json"
"zed/settings.json" = "/home/akram/.config/zed/settings.json"

[templates]
