[symlinks]
"anyrun/applications.ron" = "/home/akram/.config/anyrun/applications.ron"
"anyrun/config.ron" = "/home/akram/.config/anyrun/config.ron"
"anyrun/plugins/libanyrun_macros.so" = "/home/akram/.config/anyrun/plugins/libanyrun_macros.so"
"anyrun/plugins/libapplications.so" = "/home/akram/.config/anyrun/plugins/libapplications.so"
"anyrun/plugins/libdictionary.so" = "/home/akram/.config/anyrun/plugins/libdictionary.so"
"anyrun/plugins/libkidex.so" = "/home/akram/.config/anyrun/plugins/libkidex.so"
"anyrun/plugins/librandr.so" = "/home/akram/.config/anyrun/plugins/librandr.so"
"anyrun/plugins/librink.so" = "/home/akram/.config/anyrun/plugins/librink.so"
"anyrun/plugins/libshell.so" = "/home/akram/.config/anyrun/plugins/libshell.so"
"anyrun/plugins/libstdin.so" = "/home/akram/.config/anyrun/plugins/libstdin.so"
"anyrun/plugins/libsymbols.so" = "/home/akram/.config/anyrun/plugins/libsymbols.so"
"anyrun/plugins/libtranslate.so" = "/home/akram/.config/anyrun/plugins/libtranslate.so"
"anyrun/plugins/libwebsearch.so" = "/home/akram/.config/anyrun/plugins/libwebsearch.so"
"anyrun/style.css" = "/home/akram/.config/anyrun/style.css"
"anyrun/symbols.ron" = "/home/akram/.config/anyrun/symbols.ron"
"anyrun/websearch.ron" = "/home/akram/.config/anyrun/websearch.ron"
"eww/colors.conf" = "/home/akram/.config/eww/colors.conf"
"eww/colors.scss" = "/home/akram/.config/eww/colors.scss"
"eww/eww.scss" = "/home/akram/.config/eww/eww.scss"
"eww/eww.yuck" = "/home/akram/.config/eww/eww.yuck"
"eww/modules/backlight.yuck" = "/home/akram/.config/eww/modules/backlight.yuck"
"eww/modules/bar.yuck" = "/home/akram/.config/eww/modules/bar.yuck"
"eww/modules/bg_widgets.yuck" = "/home/akram/.config/eww/modules/bg_widgets.yuck"
"eww/modules/calendar/dateCalendar.yuck" = "/home/akram/.config/eww/modules/calendar/dateCalendar.yuck"
"eww/modules/calendar/eventManager.yuck" = "/home/akram/.config/eww/modules/calendar/eventManager.yuck"
"eww/modules/calendar/weather.yuck" = "/home/akram/.config/eww/modules/calendar/weather.yuck"
"eww/modules/calendar.yuck" = "/home/akram/.config/eww/modules/calendar.yuck"
"eww/modules/clock.yuck" = "/home/akram/.config/eww/modules/clock.yuck"
"eww/modules/control_center.yuck" = "/home/akram/.config/eww/modules/control_center.yuck"
"eww/modules/dock.yuck" = "/home/akram/.config/eww/modules/dock.yuck"
"eww/modules/expand.yuck" = "/home/akram/.config/eww/modules/expand.yuck"
"eww/modules/indicator.yuck" = "/home/akram/.config/eww/modules/indicator.yuck"
"eww/modules/info-center.yuck" = "/home/akram/.config/eww/modules/info-center.yuck"
"eww/modules/info.yuck" = "/home/akram/.config/eww/modules/info.yuck"
"eww/modules/language.yuck" = "/home/akram/.config/eww/modules/language.yuck"
"eww/modules/launcher.yuck" = "/home/akram/.config/eww/modules/launcher.yuck"
"eww/modules/logo.yuck" = "/home/akram/.config/eww/modules/logo.yuck"
"eww/modules/music.yuck" = "/home/akram/.config/eww/modules/music.yuck"
"eww/modules/notifications.yuck" = "/home/akram/.config/eww/modules/notifications.yuck"
"eww/modules/notifications_popup.yuck" = "/home/akram/.config/eww/modules/notifications_popup.yuck"
"eww/modules/others.yuck" = "/home/akram/.config/eww/modules/others.yuck"
"eww/modules/pfp.yuck" = "/home/akram/.config/eww/modules/pfp.yuck"
"eww/modules/picker.yuck" = "/home/akram/.config/eww/modules/picker.yuck"
"eww/modules/power.yuck" = "/home/akram/.config/eww/modules/power.yuck"
"eww/modules/powermenu.yuck" = "/home/akram/.config/eww/modules/powermenu.yuck"
"eww/modules/quick_settings.yuck" = "/home/akram/.config/eww/modules/quick_settings.yuck"
"eww/modules/recorder_menu.yuck" = "/home/akram/.config/eww/modules/recorder_menu.yuck"
"eww/modules/screenshot.yuck" = "/home/akram/.config/eww/modules/screenshot.yuck"
"eww/modules/taskbar.yuck" = "/home/akram/.config/eww/modules/taskbar.yuck"
"eww/modules/tray.yuck" = "/home/akram/.config/eww/modules/tray.yuck"
"eww/modules/user.yuck" = "/home/akram/.config/eww/modules/user.yuck"
"eww/modules/volume.yuck" = "/home/akram/.config/eww/modules/volume.yuck"
"eww/modules/weather.yuck" = "/home/akram/.config/eww/modules/weather.yuck"
"eww/modules/workspaces.yuck" = "/home/akram/.config/eww/modules/workspaces.yuck"
"eww/pfp.png" = "/home/akram/.config/eww/pfp.png"
"eww/scripts/apps.py" = "/home/akram/.config/eww/scripts/apps.py"
"eww/scripts/bluetooth.sh" = "/home/akram/.config/eww/scripts/bluetooth.sh"
"eww/scripts/calendar-popup.sh" = "/home/akram/.config/eww/scripts/calendar-popup.sh"
"eww/scripts/calendar.sh" = "/home/akram/.config/eww/scripts/calendar.sh"
"eww/scripts/change-wallpaper.sh" = "/home/akram/.config/eww/scripts/change-wallpaper.sh"
"eww/scripts/checkvolume.sh" = "/home/akram/.config/eww/scripts/checkvolume.sh"
"eww/scripts/colors/colors.scss" = "/home/akram/.config/eww/scripts/colors/colors.scss"
"eww/scripts/cpu" = "/home/akram/.config/eww/scripts/cpu"
"eww/scripts/disk" = "/home/akram/.config/eww/scripts/disk"
"eww/scripts/get-active-workspace.sh" = "/home/akram/.config/eww/scripts/get-active-workspace.sh"
"eww/scripts/get-battery.sh" = "/home/akram/.config/eww/scripts/get-battery.sh"
"eww/scripts/get-current-wallpaper.sh" = "/home/akram/.config/eww/scripts/get-current-wallpaper.sh"
"eww/scripts/get-hypridle-status.sh" = "/home/akram/.config/eww/scripts/get-hypridle-status.sh"
"eww/scripts/get-memory.sh" = "/home/akram/.config/eww/scripts/get-memory.sh"
"eww/scripts/get-month.sh" = "/home/akram/.config/eww/scripts/get-month.sh"
"eww/scripts/get-music-seek.sh" = "/home/akram/.config/eww/scripts/get-music-seek.sh"
"eww/scripts/get-network-strength.sh" = "/home/akram/.config/eww/scripts/get-network-strength.sh"
"eww/scripts/get-network.sh" = "/home/akram/.config/eww/scripts/get-network.sh"
"eww/scripts/get-time-left.sh" = "/home/akram/.config/eww/scripts/get-time-left.sh"
"eww/scripts/get-volume-icons.sh" = "/home/akram/.config/eww/scripts/get-volume-icons.sh"
"eww/scripts/get-wallpapers.sh" = "/home/akram/.config/eww/scripts/get-wallpapers.sh"
"eww/scripts/get-workspaces.sh" = "/home/akram/.config/eww/scripts/get-workspaces.sh"
"eww/scripts/get_kb_layout.sh" = "/home/akram/.config/eww/scripts/get_kb_layout.sh"
"eww/scripts/is-battery.sh" = "/home/akram/.config/eww/scripts/is-battery.sh"
"eww/scripts/is-brightness.sh" = "/home/akram/.config/eww/scripts/is-brightness.sh"
"eww/scripts/memory" = "/home/akram/.config/eww/scripts/memory"
"eww/scripts/mpris.sh" = "/home/akram/.config/eww/scripts/mpris.sh"
"eww/scripts/network.sh" = "/home/akram/.config/eww/scripts/network.sh"
"eww/scripts/notifications.py" = "/home/akram/.config/eww/scripts/notifications.py"
"eww/scripts/notifications.sh" = "/home/akram/.config/eww/scripts/notifications.sh"
"eww/scripts/picker.sh" = "/home/akram/.config/eww/scripts/picker.sh"
"eww/scripts/positions.sh" = "/home/akram/.config/eww/scripts/positions.sh"
"eww/scripts/powermenu.sh" = "/home/akram/.config/eww/scripts/powermenu.sh"
"eww/scripts/record.sh" = "/home/akram/.config/eww/scripts/record.sh"
"eww/scripts/screenshot" = "/home/akram/.config/eww/scripts/screenshot"
"eww/scripts/select_wallpaper.sh" = "/home/akram/.config/eww/scripts/select_wallpaper.sh"
"eww/scripts/start.sh" = "/home/akram/.config/eww/scripts/start.sh"
"eww/scripts/switch_kb_layout.sh" = "/home/akram/.config/eww/scripts/switch_kb_layout.sh"
"eww/scripts/taskbar.sh" = "/home/akram/.config/eww/scripts/taskbar.sh"
"eww/scripts/toggle_calendar.sh" = "/home/akram/.config/eww/scripts/toggle_calendar.sh"
"eww/scripts/toggle_control_center.sh" = "/home/akram/.config/eww/scripts/toggle_control_center.sh"
"eww/scripts/toggle_launcher.sh" = "/home/akram/.config/eww/scripts/toggle_launcher.sh"
"eww/scripts/toggle_osd.sh" = "/home/akram/.config/eww/scripts/toggle_osd.sh"
"eww/scripts/toggle_powermenu.sh" = "/home/akram/.config/eww/scripts/toggle_powermenu.sh"
"eww/scripts/toggle_tray.sh" = "/home/akram/.config/eww/scripts/toggle_tray.sh"
"eww/scripts/variables.yuck" = "/home/akram/.config/eww/scripts/variables.yuck"
"eww/scripts/volume.sh" = "/home/akram/.config/eww/scripts/volume.sh"
"eww/scripts/weather.py" = "/home/akram/.config/eww/scripts/weather.py"
"eww/scripts/wifi-menu.sh" = "/home/akram/.config/eww/scripts/wifi-menu.sh"
"eww/scripts/workspaces.sh" = "/home/akram/.config/eww/scripts/workspaces.sh"
"eww/scss/dark/bar.scss" = "/home/akram/.config/eww/scss/dark/bar.scss"
"eww/scss/dark/calendar.scss" = "/home/akram/.config/eww/scss/dark/calendar.scss"
"eww/scss/dark/clock.scss" = "/home/akram/.config/eww/scss/dark/clock.scss"
"eww/scss/dark/control_center.scss" = "/home/akram/.config/eww/scss/dark/control_center.scss"
"eww/scss/dark/eww.scss" = "/home/akram/.config/eww/scss/dark/eww.scss"
"eww/scss/dark/expand.scss" = "/home/akram/.config/eww/scss/dark/expand.scss"
"eww/scss/dark/indicator.scss" = "/home/akram/.config/eww/scss/dark/indicator.scss"
"eww/scss/dark/info-center.scss" = "/home/akram/.config/eww/scss/dark/info-center.scss"
"eww/scss/dark/info.scss" = "/home/akram/.config/eww/scss/dark/info.scss"
"eww/scss/dark/language.scss" = "/home/akram/.config/eww/scss/dark/language.scss"
"eww/scss/dark/launcher.scss" = "/home/akram/.config/eww/scss/dark/launcher.scss"
"eww/scss/dark/lib.scss" = "/home/akram/.config/eww/scss/dark/lib.scss"
"eww/scss/dark/logo.scss" = "/home/akram/.config/eww/scss/dark/logo.scss"
"eww/scss/dark/music.scss" = "/home/akram/.config/eww/scss/dark/music.scss"
"eww/scss/dark/notifications.scss" = "/home/akram/.config/eww/scss/dark/notifications.scss"
"eww/scss/dark/notifications_popup.scss" = "/home/akram/.config/eww/scss/dark/notifications_popup.scss"
"eww/scss/dark/picker.scss" = "/home/akram/.config/eww/scss/dark/picker.scss"
"eww/scss/dark/power.scss" = "/home/akram/.config/eww/scss/dark/power.scss"
"eww/scss/dark/powermenu.scss" = "/home/akram/.config/eww/scss/dark/powermenu.scss"
"eww/scss/dark/quick_settings.scss" = "/home/akram/.config/eww/scss/dark/quick_settings.scss"
"eww/scss/dark/screenshot.scss" = "/home/akram/.config/eww/scss/dark/screenshot.scss"
"eww/scss/dark/taskbar.scss" = "/home/akram/.config/eww/scss/dark/taskbar.scss"
"eww/scss/dark/tray.scss" = "/home/akram/.config/eww/scss/dark/tray.scss"
"eww/scss/dark/user.scss" = "/home/akram/.config/eww/scss/dark/user.scss"
"eww/scss/dark/volume.scss" = "/home/akram/.config/eww/scss/dark/volume.scss"
"eww/scss/dark/weather.scss" = "/home/akram/.config/eww/scss/dark/weather.scss"
"eww/scss/dark/workspaces.scss" = "/home/akram/.config/eww/scss/dark/workspaces.scss"
"eww/scss/light/bar.scss" = "/home/akram/.config/eww/scss/light/bar.scss"
"eww/scss/light/calendar.scss" = "/home/akram/.config/eww/scss/light/calendar.scss"
"eww/scss/light/clock.scss" = "/home/akram/.config/eww/scss/light/clock.scss"
"eww/scss/light/control_center.scss" = "/home/akram/.config/eww/scss/light/control_center.scss"
"eww/scss/light/eww.scss" = "/home/akram/.config/eww/scss/light/eww.scss"
"eww/scss/light/expand.scss" = "/home/akram/.config/eww/scss/light/expand.scss"
"eww/scss/light/indicator.scss" = "/home/akram/.config/eww/scss/light/indicator.scss"
"eww/scss/light/info-center.scss" = "/home/akram/.config/eww/scss/light/info-center.scss"
"eww/scss/light/info.scss" = "/home/akram/.config/eww/scss/light/info.scss"
"eww/scss/light/language.scss" = "/home/akram/.config/eww/scss/light/language.scss"
"eww/scss/light/launcher.scss" = "/home/akram/.config/eww/scss/light/launcher.scss"
"eww/scss/light/lib.scss" = "/home/akram/.config/eww/scss/light/lib.scss"
"eww/scss/light/logo.scss" = "/home/akram/.config/eww/scss/light/logo.scss"
"eww/scss/light/music.scss" = "/home/akram/.config/eww/scss/light/music.scss"
"eww/scss/light/notifications.scss" = "/home/akram/.config/eww/scss/light/notifications.scss"
"eww/scss/light/notifications_popup.scss" = "/home/akram/.config/eww/scss/light/notifications_popup.scss"
"eww/scss/light/picker.scss" = "/home/akram/.config/eww/scss/light/picker.scss"
"eww/scss/light/power.scss" = "/home/akram/.config/eww/scss/light/power.scss"
"eww/scss/light/powermenu.scss" = "/home/akram/.config/eww/scss/light/powermenu.scss"
"eww/scss/light/quick_settings.scss" = "/home/akram/.config/eww/scss/light/quick_settings.scss"
"eww/scss/light/screenshot.scss" = "/home/akram/.config/eww/scss/light/screenshot.scss"
"eww/scss/light/taskbar.scss" = "/home/akram/.config/eww/scss/light/taskbar.scss"
"eww/scss/light/tray.scss" = "/home/akram/.config/eww/scss/light/tray.scss"
"eww/scss/light/user.scss" = "/home/akram/.config/eww/scss/light/user.scss"
"eww/scss/light/volume.scss" = "/home/akram/.config/eww/scss/light/volume.scss"
"eww/scss/light/weather.scss" = "/home/akram/.config/eww/scss/light/weather.scss"
"eww/scss/light/workspaces.scss" = "/home/akram/.config/eww/scss/light/workspaces.scss"
"eww/variables.yuck" = "/home/akram/.config/eww/variables.yuck"
"eww/windows.yuck" = "/home/akram/.config/eww/windows.yuck"
"fish/auto-Hypr.fish" = "/home/akram/.config/fish/auto-Hypr.fish"
"fish/config.fish" = "/home/akram/.config/fish/config.fish"
"fish/fish_variables" = "/home/akram/.config/fish/fish_variables"
"fish/functions/fish_prompt.fish" = "/home/akram/.config/fish/functions/fish_prompt.fish"
"fuzzel/fuzzel.ini" = "/home/akram/.config/fuzzel/fuzzel.ini"
"hypr/custom/env.conf" = "/home/akram/.config/hypr/custom/env.conf"
"hypr/custom/execs.conf" = "/home/akram/.config/hypr/custom/execs.conf"
"hypr/custom/general.conf" = "/home/akram/.config/hypr/custom/general.conf"
"hypr/custom/keybinds.conf" = "/home/akram/.config/hypr/custom/keybinds.conf"
"hypr/custom/rules.conf" = "/home/akram/.config/hypr/custom/rules.conf"
"hypr/hypridle.conf" = "/home/akram/.config/hypr/hypridle.conf"
"hypr/hyprland/awkvars.out" = "/home/akram/.config/hypr/hyprland/awkvars.out"
"hypr/hyprland/colors.conf" = "/home/akram/.config/hypr/hyprland/colors.conf"
"hypr/hyprland/env.conf" = "/home/akram/.config/hypr/hyprland/env.conf"
"hypr/hyprland/execs.conf" = "/home/akram/.config/hypr/hyprland/execs.conf"
"hypr/hyprland/general.conf" = "/home/akram/.config/hypr/hyprland/general.conf"
"hypr/hyprland/keybinds.conf" = "/home/akram/.config/hypr/hyprland/keybinds.conf"
"hypr/hyprland/rules.conf" = "/home/akram/.config/hypr/hyprland/rules.conf"
"hypr/hyprland.conf" = "/home/akram/.config/hypr/hyprland.conf"
"hypr/hyprlock/status.sh" = "/home/akram/.config/hypr/hyprlock/status.sh"
"hypr/hyprlock.conf" = "/home/akram/.config/hypr/hyprlock.conf"
"hypr/scripts/touchpad_toggle.sh" = "/home/akram/.config/hypr/scripts/touchpad_toggle.sh"
"hypr/shaders/chromatic_abberation.frag" = "/home/akram/.config/hypr/shaders/chromatic_abberation.frag"
"hypr/shaders/crt.frag" = "/home/akram/.config/hypr/shaders/crt.frag"
"hypr/shaders/drugs.frag" = "/home/akram/.config/hypr/shaders/drugs.frag"
"hypr/shaders/extradark.frag" = "/home/akram/.config/hypr/shaders/extradark.frag"
"hypr/shaders/invert.frag" = "/home/akram/.config/hypr/shaders/invert.frag"
"hypr/shaders/solarized.frag" = "/home/akram/.config/hypr/shaders/solarized.frag"
"matugen/config.toml" = "/home/akram/.config/matugen/config.toml"
"matugen/templates/_color.txt" = "/home/akram/.config/matugen/templates/_color.txt"
"matugen/templates/_material_template.scss" = "/home/akram/.config/matugen/templates/_material_template.scss"
"matugen/templates/fuzzel/fuzzel.ini" = "/home/akram/.config/matugen/templates/fuzzel/fuzzel.ini"
"matugen/templates/gtk_colors.css" = "/home/akram/.config/matugen/templates/gtk_colors.css"
"matugen/templates/gtk_template.css" = "/home/akram/.config/matugen/templates/gtk_template.css"
"matugen/templates/gtk_template_ex_backup.css" = "/home/akram/.config/matugen/templates/gtk_template_ex_backup.css"
"matugen/templates/hypr/hyprland/colors.conf" = "/home/akram/.config/matugen/templates/hypr/hyprland/colors.conf"
"matugen/templates/hypr/hyprlock.conf" = "/home/akram/.config/matugen/templates/hypr/hyprlock.conf"
"starship/starship.toml" = "/home/akram/.config/starship/starship.toml"
"wezterm.lua" = "/home/akram/.wezterm.lua"
"zed/keymap.json" = "/home/akram/.config/zed/keymap.json"
"zed/settings.json" = "/home/akram/.config/zed/settings.json"

[templates]
