[symlinks]
"fish/config.fish" = "/home/akram/.config/fish/config.fish"
"fish/fish_variables" = "/home/akram/.config/fish/fish_variables"
"fish/functions/fish_prompt.fish" = "/home/akram/.config/fish/functions/fish_prompt.fish"
"fontconfig/fonts.conf" = "/home/akram/.config/fontconfig/fonts.conf"
"foot/foot.ini" = "/home/akram/.config/foot/foot.ini"
"helix/config.toml" = "/home/akram/.config/helix/config.toml"
"helix/languages.toml" = "/home/akram/.config/helix/languages.toml"
"hypr/hypridle.conf" = "/home/akram/.config/hypr/hypridle.conf"
"hypr/hyprland.conf" = "/home/akram/.config/hypr/hyprland.conf"
"hypr/hyprlock/battery.sh" = "/home/akram/.config/hypr/hyprlock/battery.sh"
"hypr/hyprlock.conf" = "/home/akram/.config/hypr/hyprlock.conf"
"hypr/hyprlux.toml" = "/home/akram/.config/hypr/hyprlux.toml"
"hypr/local/local.conf" = "/home/akram/.config/hypr/local/local.conf"
"hypr/modules/animations/END-4.conf" = "/home/akram/.config/hypr/modules/animations/END-4.conf"
"hypr/modules/animations/HYDE - Vertical.conf" = "/home/akram/.config/hypr/modules/animations/HYDE - Vertical.conf"
"hypr/modules/animations/HYDE - default.conf" = "/home/akram/.config/hypr/modules/animations/HYDE - default.conf"
"hypr/modules/animations/HYDE - minimal-1.conf" = "/home/akram/.config/hypr/modules/animations/HYDE - minimal-1.conf"
"hypr/modules/animations/HYDE - minimal-2.conf" = "/home/akram/.config/hypr/modules/animations/HYDE - minimal-2.conf"
"hypr/modules/animations/HYDE - optimized.conf" = "/home/akram/.config/hypr/modules/animations/HYDE - optimized.conf"
"hypr/modules/animations/ML4W - classic.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - classic.conf"
"hypr/modules/animations/ML4W - dynamic.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - dynamic.conf"
"hypr/modules/animations/ML4W - fast.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - fast.conf"
"hypr/modules/animations/ML4W - high.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - high.conf"
"hypr/modules/animations/ML4W - moving.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - moving.conf"
"hypr/modules/animations/ML4W - standard.conf" = "/home/akram/.config/hypr/modules/animations/ML4W - standard.conf"
"hypr/modules/animations/Mahaveer - me-1.conf" = "/home/akram/.config/hypr/modules/animations/Mahaveer - me-1.conf"
"hypr/modules/animations/Mahaveer - me-2.conf" = "/home/akram/.config/hypr/modules/animations/Mahaveer - me-2.conf"
"hypr/modules/animations/Matuprland optimized.conf" = "/home/akram/.config/hypr/modules/animations/Matuprland optimized.conf"
"hypr/modules/animations/default - v2.conf" = "/home/akram/.config/hypr/modules/animations/default - v2.conf"
"hypr/modules/animations/default.conf" = "/home/akram/.config/hypr/modules/animations/default.conf"
"hypr/modules/animations/disabled.conf" = "/home/akram/.config/hypr/modules/animations/disabled.conf"
"hypr/modules/animations.conf" = "/home/akram/.config/hypr/modules/animations.conf"
"hypr/modules/autostart.conf" = "/home/akram/.config/hypr/modules/autostart.conf"
"hypr/modules/decorations.conf" = "/home/akram/.config/hypr/modules/decorations.conf"
"hypr/modules/inputs.conf" = "/home/akram/.config/hypr/modules/inputs.conf"
"hypr/modules/keybinds.conf" = "/home/akram/.config/hypr/modules/keybinds.conf"
"hypr/modules/monitors.conf" = "/home/akram/.config/hypr/modules/monitors.conf"
"hypr/modules/programs.conf" = "/home/akram/.config/hypr/modules/programs.conf"
"hypr/modules/settings.conf" = "/home/akram/.config/hypr/modules/settings.conf"
"hypr/modules/variables.conf" = "/home/akram/.config/hypr/modules/variables.conf"
"hypr/modules/windowrules.conf" = "/home/akram/.config/hypr/modules/windowrules.conf"
"hypr/modules/workspacerules.conf" = "/home/akram/.config/hypr/modules/workspacerules.conf"
"matugen/config.toml" = "/home/akram/.config/matugen/config.toml"
"matugen/templates/colors" = "/home/akram/.config/matugen/templates/colors"
"matugen/templates/colors-hyprland" = "/home/akram/.config/matugen/templates/colors-hyprland"
"matugen/templates/gtk" = "/home/akram/.config/matugen/templates/gtk"
"matugen/templates/shell/shell-dark" = "/home/akram/.config/matugen/templates/shell/shell-dark"
"matugen/templates/shell/shell-light" = "/home/akram/.config/matugen/templates/shell/shell-light"
"nushell/config.nu" = "/home/akram/.config/nushell/config.nu"
"nushell/env.nu" = "/home/akram/.config/nushell/env.nu"
"nushell/history.txt" = "/home/akram/.config/nushell/history.txt"
"scripts/backlight" = "/home/akram/.local/bin/backlight"
"scripts/color-picker" = "/home/akram/.local/bin/color-picker"
"scripts/kill-active-processes" = "/home/akram/.local/bin/kill-active-processes"
"scripts/resetxdgportal.sh" = "/home/akram/.local/bin/resetxdgportal.sh"
"scripts/shell-colors" = "/home/akram/.local/bin/shell-colors"
"scripts/switch-color" = "/home/akram/.local/bin/switch-color"
"scripts/switch-darklight" = "/home/akram/.local/bin/switch-darklight"
"scripts/switch-wallpaper" = "/home/akram/.local/bin/switch-wallpaper"
"scripts/volume" = "/home/akram/.local/bin/volume"
"sherlock/config.toml" = "/home/akram/.config/sherlock/config.toml"
"sherlock/fallback.json" = "/home/akram/.config/sherlock/fallback.json"
"sherlock/main.css" = "/home/akram/.config/sherlock/main.css"
"sherlock/sherlock_alias.json" = "/home/akram/.config/sherlock/sherlock_alias.json"
"sherlock/sherlockignore" = "/home/akram/.config/sherlock/sherlockignore"
"starship/starship.toml" = "/home/akram/.config/starship/starship.toml"
"swaync/config.json" = "/home/akram/.config/swaync/config.json"
"swaync/style.css" = "/home/akram/.config/swaync/style.css"
"swaync/styles/central_control.css" = "/home/akram/.config/swaync/styles/central_control.css"
"swaync/styles/notifications.css" = "/home/akram/.config/swaync/styles/notifications.css"
"waybar/config.jsonc" = "/home/akram/.config/waybar/config.jsonc"
"waybar/style.css" = "/home/akram/.config/waybar/style.css"
"xdg-terminals.list" = "/home/akram/.config/xdg-terminals.list"
"zed/keymap.json" = "/home/akram/.config/zed/keymap.json"
"zed/settings.json" = "/home/akram/.config/zed/settings.json"

[templates]
