[helpers]

[default]
depends = []

[default.files]
btop = "~/.config/btop/"
fastfetch = "~/.config/fastfetch/"
fish = "~/.config/fish/"
fontconfig = "~/.config/fontconfig/"
foot = "~/.config/foot/"
helix = "~/.config/helix/"
hypr = "~/.config/hypr/"
matugen = "~/.config/matugen/"
nushell = "~/.config/nushell/"
starship = "~/.config/starship"
scripts = "~/.local/bin"
rofi = "~/.config/rofi"
waybar = "~/.config/waybar/"
swaync = "~/.config/swaync"
"xdg-terminals.list" = "~/.config/xdg-terminals.list"
"keymapper.conf" = "~/.config/keymapper.conf"

[default.variables]

[settings]
default_target_type = "symbolic"
