[helpers]

[default]
depends = []

[default.files]
# ags = "~/.config/ags"
eww = "~/.config/eww/"
anyrun = "~/.config/anyrun/"
fish = "~/.config/fish/"
fuzzel = "~/.config/fuzzel/"
hypr = "~/.config/hypr/"
matugen = "~/.config/matugen/"
starship = "~/.config/starship"
zed = "~/.config/zed"
"wezterm.lua" = "~/.wezterm.lua"

[default.variables]

[settings]
default_target_type = "symbolic"
