[helpers]

[default]
depends = []

[default.files]
fish = "~/.config/fish/"
fontconfig = "~/.config/fontconfig/"
foot = "~/.config/foot/"
helix = "~/.config/helix/"
hypr = "~/.config/hypr/"
matugen = "~/.config/matugen/"
nushell = "~/.config/nushell/"
starship = "~/.config/starship"
sherlock = "~/.config/sherlock"
scripts = "~/.local/bin"
waybar = "~/.config/waybar/"
swaync = "~/.config/swaync"
zed = "~/.config/zed/"
"xdg-terminals.list" = "~/.config/xdg-terminals.list"

[default.variables]

[settings]
default_target_type = "symbolic"
