[helpers]

[default]
depends = []

[default.files]
ags = "~/.config/ags"
anyrun = "~/.config/anyrun/"
fish = "~/.config/fish/"
fuzzel = "~/.config/fuzzel/"
hypr = "~/.config/hypr/"
matugen = "~/.config/matugen/"
"starship.toml" = "~/.config/starship.toml"
zed = "~/.config/zed"
"wezterm.lua" = "~/.wezterm.lua"

[default.variables]

[settings]
default_target_type = "automatic"
