[helpers]

[default]
depends = []

[default.files]
anyrun = "~/.config/anyrun/"
dunst = "~/.config/dunst/"
fish = "~/.config/fish/"
fontconfig = "~/.config/fontconfig/"
foot = "~/.config/foot/"
helix = "~/.config/helix/"
hypr = "~/.config/hypr/"
matugen = "~/.config/matugen/"
nushell = "~/.config/nushell/"
starship = "~/.config/starship"
qt6ct = "~/.config/qt6ct/"
waybar = "~/.config/waybar/"
zed = "~/.config/zed/"
"wezterm.lua" = "~/.wezterm.lua"
"xdg-terminals.list" = "~/.config/xdg-terminals.list"

[default.variables]

[settings]
default_target_type = "symbolic"
