[helpers]

[default]
depends = []

[default.files]
anyrun = "~/.config/anyrun/"
fish = "~/.config/fish/"
fontconfig = "~/.config/fontconfig/"
helix = "~/.config/helix/"
hypr = "~/.config/hypr/"
matugen = "~/.config/matugen/"
nushell = "~/.config/nushell"
starship = "~/.config/starship"
qt6ct = "~/.config/qt6ct/"
zed = "~/.config/zed"
"wezterm.lua" = "~/.wezterm.lua"

[default.variables]

[settings]
default_target_type = "symbolic"
